### ISSUE TITLE
Incoming fixes and configuring contributors

### ISSUE THREAD

**Issue by aloutfi** [sylfort/journal-with-auth#2]
Heya Sylfort! I'm Deija's partner Andrew. She invited me to see if I could assist y'all with your project.

Whilst trying to spin up the repo, I ran into some issues and made some changes to get it to work. They were disseminated to the group during the meeting. Feel free to [merge my pull request](https://github.com/sylfort/journal-with-auth/pull/1) they are in.

I think a solid step would be to [add contributors to this repository](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository). This will allow folks to push and pull from a centralized place (as opposed to forks, where it might be difficult for the team to keep their code up to date)

 Then, set up branch protections on the main branch. This is within the security settings for the repo. 

I'm happy to talk through any questions you have or would even be happy to do a coffee chat :) DM me on twitter [@loutfi_o](https://twitter.com/loutfi_o)

**Comment by sylfort** [comment]
Hi Andrew, thanks for your email!

I merged your PR. Please add me on Twitter: @sylfort1

Thanks for the help, I will need more for sure.

Best Regards
Sylvio Mafort
